# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"make_generic_rolling_features": "rolling.ipynb",
         "make_generic_resampling_and_shift_features": "rolling.ipynb",
         "create_rolling_resampled_features": "rolling.ipynb"}

modules = ["rolling.py"]

doc_url = "https://AlanGanem.github.io/see_me_rolling/"

git_url = "https://github.com/AlanGanem/see_me_rolling/tree/{branch}/"

def custom_doc_links(name): return None
